##### MongoDB ############
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/admin
spring.data.mongodb.repositories.enabled=true
spring.data.mongodb.prefix=tnt

spring.ro.data.mongodb.uri=${spring.data.mongodb.uri}
spring.ro.data.mongodb.repositories.enabled=${spring.data.mongodb.repositories.enabled}
spring.ro.data.mongodb.prefix=${spring.data.mongodb.prefix}

