##### MongoDB ############
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/admin
spring.data.mongodb.repositories.enabled=true
spring.data.mongodb.prefix=tnt
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017