<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>bootjx-common-lib</artifactId>
	<packaging>jar</packaging>
	<name>bootjx-common-lib</name>
	<url>http://maven.apache.org</url>
	<description>Common Spring boot lib  for amx projects</description>

	<parent>
		<groupId>com.boot.jx</groupId>
		<artifactId>bootjx-common</artifactId>
		<version>2.0.3-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<properties>
		<buildtimestamp>${maven.build.timestamp}</buildtimestamp>
		<maven.build.timestamp.format>yyyy-MM-dd HH:mm z</maven.build.timestamp.format>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<swagger.version>2.8.0</swagger.version>
		<jasypt.spring.version>3.0.0</jasypt.spring.version>
	</properties>

	<dependencies>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
		</dependency>

		<dependency>
			<groupId>com.boot.jx</groupId>
			<artifactId>bootjx-common-utils</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.mobile</groupId>
			<artifactId>spring-mobile-device</artifactId>
			<version>2.0.0.M3</version>
		</dependency>

		<dependency>
			<groupId>eu.bitwalker</groupId>
			<artifactId>UserAgentUtils</artifactId>
			<version>1.21</version>
		</dependency>

		<dependency>
			<groupId>com.googlecode.owasp-java-html-sanitizer</groupId>
			<artifactId>owasp-java-html-sanitizer</artifactId>
			<version>20200713.1</version>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>${swagger.version}</version>
			<!-- <scope>compile</scope> -->
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>${swagger.version}</version>
			<!-- <scope>compile</scope> -->
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-spi</artifactId>
			<version>${swagger.version}</version>
		</dependency>

<!-- 
		<dependency>
			<groupId>com.boot.jx</groupId>
			<artifactId>boot-ext-jar</artifactId>
			<type>pom</type>
		</dependency>
-->
		<dependency>
			<groupId>com.boot.jx</groupId>
			<artifactId>bootjx-extjar</artifactId>
			<type>pom</type>
		</dependency>
		
		<dependency>
			<groupId>com.github.ulisesbocchio</groupId>
			<artifactId>jasypt-spring-boot</artifactId>
			<version>${jasypt.spring.version}</version>
		</dependency> 
		
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.5</version>
		</dependency>

		<!-- org.apache.commons.lang.* call sites migrated to lang3; version
			inherited from the Spring Boot 2.0.5 BOM (3.7). -->
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
		</dependency>

		<dependency>
			<groupId>com.github.gianluca-nitti</groupId>
			<artifactId>java-expr-eval</artifactId>
			<version>v3.1</version>
		</dependency>

		<!-- https://stackoverflow.com/questions/61501810/javadoc-error-datatypeconverter-doesnot-exist -->
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<version>2.3.3</version>
		</dependency>

		<!-- file upload libs start -->
		<dependency>
			<groupId>org.springframework.integration</groupId>
			<artifactId>spring-integration-http</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.9.0</version>
		</dependency>
		<!-- file upload libs ends -->

		<dependency>
			<groupId>com.googlecode.libphonenumber</groupId>
			<artifactId>libphonenumber</artifactId>
			<version>8.10.5</version>
		</dependency>

	</dependencies>

	<repositories>
		<repository>
			<id>jcenter-snapshots</id>
			<name>jcenter</name>
			<url>https://jcenter.bintray.com/</url>
		</repository>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
		<repository>
			<id>spring-repo</id>
			<name>Spring Plugins</name>
			<url>https://repo.spring.io/plugins-release</url>
		</repository>
	</repositories>

</project>
